In [1]:
import tensorflow as tf

In [3]:
model = tf.keras.models.load_model("./checkpoint")

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 7, 7, 512)         14714688  
                                                                 
 global_average_pooling2d (G  (None, 512)              0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 2048)              1050624   
                                                                 
 dense_1 (Dense)             (None, 1024)              2098176   
                                                                 
 dense_2 (Dense)             (None, 512)               524800    
                                                                 
 dense_3 (Dense)             (None, 51)                26163     
                                                        

In [5]:
import numpy as np

img = tf.keras.utils.load_img("./utilityspace/current.jpeg")
img_tensor = tf.keras.preprocessing.image.img_to_array(img)
img_array_expanded_dims = np.expand_dims(img_tensor, axis=0)
print(img_array_expanded_dims)

[[[[200. 183. 167.]
   [198. 181. 165.]
   [197. 180. 162.]
   ...
   [176. 181. 159.]
   [160. 165. 143.]
   [161. 166. 144.]]

  [[201. 184. 168.]
   [199. 182. 166.]
   [198. 181. 163.]
   ...
   [169. 174. 152.]
   [162. 167. 145.]
   [154. 159. 137.]]

  [[201. 184. 166.]
   [200. 183. 165.]
   [199. 182. 164.]
   ...
   [165. 170. 148.]
   [168. 173. 151.]
   [154. 159. 137.]]

  ...

  [[213. 157. 122.]
   [210. 156. 120.]
   [206. 153. 121.]
   ...
   [138. 125. 106.]
   [145. 130. 111.]
   [152. 137. 118.]]

  [[209. 155. 117.]
   [206. 152. 114.]
   [204. 151. 117.]
   ...
   [137. 124. 105.]
   [144. 129. 110.]
   [153. 138. 119.]]

  [[206. 153. 113.]
   [204. 152. 113.]
   [204. 151. 117.]
   ...
   [137. 124. 105.]
   [144. 129. 110.]
   [154. 139. 120.]]]]


In [8]:
preprocessed = tf.keras.applications.vgg16.preprocess_input(img_array_expanded_dims)

In [11]:
print(preprocessed)
face_prediction = model.predict(preprocessed)

[[[[63.060997  66.221     76.32     ]
   [61.060997  64.221     74.32     ]
   [58.060997  63.221     73.32     ]
   ...
   [55.060997  64.221     52.32     ]
   [39.060997  48.221     36.32     ]
   [40.060997  49.221     37.32     ]]

  [[64.061     67.221     77.32     ]
   [62.060997  65.221     75.32     ]
   [59.060997  64.221     74.32     ]
   ...
   [48.060997  57.221     45.32     ]
   [41.060997  50.221     38.32     ]
   [33.060997  42.221     30.32     ]]

  [[62.060997  67.221     77.32     ]
   [61.060997  66.221     76.32     ]
   [60.060997  65.221     75.32     ]
   ...
   [44.060997  53.221     41.32     ]
   [47.060997  56.221     44.32     ]
   [33.060997  42.221     30.32     ]]

  ...

  [[18.060997  40.221     89.32     ]
   [16.060997  39.221     86.32     ]
   [17.060997  36.221     82.32     ]
   ...
   [ 2.060997   8.221001  14.32     ]
   [ 7.060997  13.221001  21.32     ]
   [14.060997  20.221     28.32     ]]

  [[13.060997  38.221     85.32     ]
   [10.

In [13]:
np.argmax(face_prediction, axis=-1)

array([30])